<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="Views\**" />
    <Page Remove="Views\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Bold.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-BoldItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Italic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Regular.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Black.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BlackItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Bold.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BoldItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Italic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Light.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-LightItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Medium.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-MediumItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Regular.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Thin.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-ThinItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Bold.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-BoldItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Italic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Light.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-LightItalic.ttf" />
    <Content Remove="C:\Users\koval\.nuget\packages\materialdesignthemes\5.4.0-ci1482\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MaterialDesignColors" Version="5.4.0-ci1482" />
    <PackageReference Include="MaterialDesignThemes" Version="5.4.0-ci1482" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-rc.1.26425.128" />
  </ItemGroup>

</Project>
